server:
  port: 8082

## URL Rest Services applicacion
coins:
  baseURL: 'api/coins'
  healthAPI: '/health-api'
  contractAddressId: '/{id}/contract/{contractAddress}'
  contractAddressByIdMarketChart: '/{id}/contract/{contractAddress}/marketChart/'
  contractAddressByIdMarketChartByRange: '/{id}/contract/{contractAddress}/marketChart/range/'

## Url Coin Gecko RestService
api:
  urlCoinGecko: 'https://api.coingecko.com/api/v3'
  ping: '/ping'
  contractAddressById: '/coins/%s/contract/%s'
  contractAddressByIdMarketChart: '/coins/%s/contract/%s/market_chart/'
  contractAddressByIdMarketChartByRange: '/coins/%s/contract/%s/market_chart/range'
